-- Migration patch to align existing tables with current PHP queries

ALTER TABLE gym_goers
    ADD COLUMN IF NOT EXISTS fitness_goal VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS membership_plan INT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS preferred_trainer VARCHAR(100) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS gym_username VARCHAR(100) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS meal_plan INT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS workout_plan INT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS profile_picture VARCHAR(255) DEFAULT NULL;

ALTER TABLE trainers
    ADD COLUMN IF NOT EXISTS specialization VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS experience VARCHAR(100) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS certifications TEXT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS gym_username VARCHAR(100) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS fee DECIMAL(10,2) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS profile_picture VARCHAR(255) DEFAULT NULL;

ALTER TABLE sellers
    ADD COLUMN IF NOT EXISTS shipping_fee DECIMAL(10,2) DEFAULT NULL;

ALTER TABLE meal_plans
    ADD COLUMN IF NOT EXISTS meal_schedule TEXT DEFAULT NULL;
